name: check-proxies-schedule

on:
  schedule:
   - cron: "0 */1 * * *"
  push:
     paths:
      - '.github/**'
  # Manual triggers with workflow_dispatch
  workflow_dispatch:

jobs:
  check-row-urls:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.GG_GITHUB_TOKEN }}
      REPO: ${{ secrets.REPO }}
      DEBUG_MODE: 0
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: check urls
        run: python checkProxies.py
        shell: bash
